const nodemailer = require('nodemailer');

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS
  }
});

app.post('/api/send-report', async (req, res) => {
  try {
    const { email, report } = req.body;

    const getRiskColor = (level) => {
      if (level === 'Low') return '#22c55e';
      if (level === 'Medium') return '#f59e0b';
      if (level === 'High') return '#f97316';
      return '#ef4444';
    };

    const htmlContent = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #0f172a; color: #e2e8f0; padding: 24px; border-radius: 12px;">
      <div style="text-align: center; margin-bottom: 24px;">
        <h1 style="color: #6366f1; font-size: 24px; margin: 0;">🛡️ CyberRisk Assessor</h1>
        <p style="color: #94a3b8; margin: 8px 0 0;">Cybersecurity Risk Assessment Report</p>
      </div>

      <div style="background: #1e293b; border-radius: 12px; padding: 20px; margin-bottom: 20px; text-align: center;">
        <h2 style="color: #f1f5f9; margin: 0 0 8px;">${report.companyName}</h2>
        <p style="color: #94a3b8; margin: 0 0 16px;">${report.industry}</p>
        <div style="display: inline-block; background: ${getRiskColor(report.riskLevel)}22; border: 2px solid ${getRiskColor(report.riskLevel)}; border-radius: 12px; padding: 12px 24px;">
          <div style="font-size: 36px; font-weight: 800; color: ${getRiskColor(report.riskLevel)};">${report.overallRiskScore}</div>
          <div style="color: #94a3b8; font-size: 12px;">Overall Risk Score</div>
          <div style="background: ${getRiskColor(report.riskLevel)}; color: white; padding: 4px 12px; border-radius: 99px; font-size: 12px; font-weight: 600; margin-top: 8px; display: inline-block;">${report.riskLevel} Risk</div>
        </div>
      </div>

      <div style="background: #1e293b; border-radius: 12px; padding: 20px; margin-bottom: 20px;">
        <h3 style="color: #6366f1; margin: 0 0 12px;">Executive Summary</h3>
        <p style="color: #94a3b8; line-height: 1.6; margin: 0;">${report.executiveSummary}</p>
      </div>

      <div style="background: #1e293b; border-radius: 12px; padding: 20px; margin-bottom: 20px;">
        <h3 style="color: #6366f1; margin: 0 0 12px;">Top Threats Identified</h3>
        ${report.threats.map(t => `
          <div style="border-left: 3px solid ${getRiskColor(t.severity)}; padding: 8px 12px; margin-bottom: 8px; background: #0f172a; border-radius: 0 8px 8px 0;">
            <div style="display: flex; justify-content: space-between; align-items: center;">
              <strong style="color: #f1f5f9;">${t.name}</strong>
              <span style="color: ${getRiskColor(t.severity)}; font-size: 12px; font-weight: 600;">${t.severity}</span>
            </div>
            <p style="color: #94a3b8; font-size: 13px; margin: 4px 0 0;">${t.description}</p>
          </div>
        `).join('')}
      </div>

      <div style="background: #1e293b; border-radius: 12px; padding: 20px; margin-bottom: 20px;">
        <h3 style="color: #6366f1; margin: 0 0 12px;">Top Recommendations</h3>
        <ol style="color: #94a3b8; padding-left: 20px; line-height: 1.8;">
          ${report.topRecommendations.map(r => `<li>${r}</li>`).join('')}
        </ol>
      </div>

      <div style="text-align: center; padding-top: 16px; border-top: 1px solid #334155;">
        <p style="color: #64748b; font-size: 12px; margin: 0;">Generated by CyberRisk Assessor</p>
        <p style="color: #64748b; font-size: 12px; margin: 4px 0 0;">
          <a href="https://cyber-risk-tool.vercel.app" style="color: #6366f1;">cyber-risk-tool.vercel.app</a>
        </p>
      </div>
    </div>`;

    await transporter.sendMail({
      from: `"CyberRisk Assessor" <${process.env.EMAIL_USER}>`,
      to: email,
      subject: `🛡️ Cybersecurity Risk Report — ${report.companyName} (${report.riskLevel} Risk)`,
      html: htmlContent
    });

    res.json({ success: true, message: 'Report sent successfully!' });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});